[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[features.seeds]
locksmith = ["no-idl", "no-log-ix-name"]

[programs.localnet]
locksmith = "5fPbdosJd9P1gth7r9kmqc7gkgQzM2PfQHkXtQXcQyty"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
